<?php
class ContextoAnswersForm extends AbstractForm{

	public function addForm(){

		$this -> hidden('action', 'add');
		echo("<table width='100%' border='0' class='tableForm'>");
		$this -> formHeader('Agregar');
		$this -> entryText('Id','id', '','');
		$this -> entryText('Student','student', '','');
		$this -> entryText('Folio','folio', '','');
		$this -> entryText('Cct','cct', '','');
		$this -> entryText('P1O1','P1O1', '','');
		$this -> entryText('P1O2','P1O2', '','');
		$this -> entryText('P2O1','P2O1', '','');
		$this -> entryText('P2O2','P2O2', '','');
		$this -> entryText('P2O3','P2O3', '','');
		$this -> entryText('P2O4','P2O4', '','');
		$this -> entryText('P2O5','P2O5', '','');
		$this -> entryText('P2O6','P2O6', '','');
		$this -> entryText('P4O1','P4O1', '','');
		$this -> entryText('P4O2','P4O2', '','');
		$this -> entryText('P4O3','P4O3', '','');
		$this -> entryText('P4O4','P4O4', '','');
		$this -> entryText('P4O5','P4O5', '','');
		$this -> entryText('P4O6','P4O6', '','');
		$this -> entryText('P4O7','P4O7', '','');
		$this -> entryText('P4O8','P4O8', '','');
		$this -> entryText('P5O','P5O', '','');
		$this -> entryText('P6O1','P6O1', '','');
		$this -> entryText('P6O2','P6O2', '','');
		$this -> entryText('P6O3','P6O3', '','');
		$this -> entryText('P6O4','P6O4', '','');
		$this -> entryText('P7O1','P7O1', '','');
		$this -> entryText('P7O2','P7O2', '','');
		$this -> entryText('P7O3','P7O3', '','');
		$this -> entryText('P7O5','P7O5', '','');
		$this -> entryText('P7O4','P7O4', '','');
		$this -> entryText('P7O7','P7O7', '','');
		$this -> entryText('P7O6','P7O6', '','');
		$this -> entryText('P8O1','P8O1', '','');
		$this -> entryText('P8O2','P8O2', '','');
		$this -> entryText('P8O3','P8O3', '','');
		$this -> entryText('P8O4','P8O4', '','');
		$this -> entryText('P8O5','P8O5', '','');
		$this -> entryText('P9O1','P9O1', '','');
		$this -> entryText('P9O2','P9O2', '','');
		$this -> entryText('P9O3','P9O3', '','');
		$this -> entryText('P9O4','P9O4', '','');
		$this -> entryText('P10O1','P10O1', '','');
		$this -> entryText('P10O2','P10O2', '','');
		$this -> entryText('P10O3','P10O3', '','');
		$this -> entryText('P10O4','P10O4', '','');
		$this -> entryText('P10O5','P10O5', '','');
		$this -> entryText('P11O1','P11O1', '','');
		$this -> entryText('P11O2','P11O2', '','');
		$this -> entryText('P11O3','P11O3', '','');
		$this -> entryText('P11O4','P11O4', '','');
		$this -> entryText('P11O5','P11O5', '','');
		$this -> entryText('P11O6','P11O6', '','');
		$this -> entryText('P11O7','P11O7', '','');
		$this -> entryText('P11O8','P11O8', '','');
		$this -> entryText('P14O1','P14O1', '','');
		$this -> entryText('P14O2','P14O2', '','');
		$this -> entryText('P14O3','P14O3', '','');
		$this -> entryText('P14O4','P14O4', '','');
		$this -> entryText('P14O5','P14O5', '','');
		$this -> entryText('P14O6','P14O6', '','');
		$this -> entryText('P14O7','P14O7', '','');
		$this -> entryText('P14O8','P14O8', '','');
		$this -> entryText('P14O9','P14O9', '','');
		$this -> entryText('P14O10','P14O10', '','');
		$this -> entryText('P14O11','P14O11', '','');
		echo("</table>");
	}

	public function editForm(ContextoAnswers $entity){

		$this -> hidden('action', 'edit');
		echo("<table width='100%' border='0' class='tableForm'>");
		$this -> formHeader('Editar');
		$this -> entryText('Id','id', '','');
		$this -> entryText('Student','student', '','');
		$this -> entryText('Folio','folio', '','');
		$this -> entryText('Cct','cct', '','');
		$this -> entryText('P1O1','P1O1', '','');
		$this -> entryText('P1O2','P1O2', '','');
		$this -> entryText('P2O1','P2O1', '','');
		$this -> entryText('P2O2','P2O2', '','');
		$this -> entryText('P2O3','P2O3', '','');
		$this -> entryText('P2O4','P2O4', '','');
		$this -> entryText('P2O5','P2O5', '','');
		$this -> entryText('P2O6','P2O6', '','');
		$this -> entryText('P4O1','P4O1', '','');
		$this -> entryText('P4O2','P4O2', '','');
		$this -> entryText('P4O3','P4O3', '','');
		$this -> entryText('P4O4','P4O4', '','');
		$this -> entryText('P4O5','P4O5', '','');
		$this -> entryText('P4O6','P4O6', '','');
		$this -> entryText('P4O7','P4O7', '','');
		$this -> entryText('P4O8','P4O8', '','');
		$this -> entryText('P5O','P5O', '','');
		$this -> entryText('P6O1','P6O1', '','');
		$this -> entryText('P6O2','P6O2', '','');
		$this -> entryText('P6O3','P6O3', '','');
		$this -> entryText('P6O4','P6O4', '','');
		$this -> entryText('P7O1','P7O1', '','');
		$this -> entryText('P7O2','P7O2', '','');
		$this -> entryText('P7O3','P7O3', '','');
		$this -> entryText('P7O5','P7O5', '','');
		$this -> entryText('P7O4','P7O4', '','');
		$this -> entryText('P7O7','P7O7', '','');
		$this -> entryText('P7O6','P7O6', '','');
		$this -> entryText('P8O1','P8O1', '','');
		$this -> entryText('P8O2','P8O2', '','');
		$this -> entryText('P8O3','P8O3', '','');
		$this -> entryText('P8O4','P8O4', '','');
		$this -> entryText('P8O5','P8O5', '','');
		$this -> entryText('P9O1','P9O1', '','');
		$this -> entryText('P9O2','P9O2', '','');
		$this -> entryText('P9O3','P9O3', '','');
		$this -> entryText('P9O4','P9O4', '','');
		$this -> entryText('P10O1','P10O1', '','');
		$this -> entryText('P10O2','P10O2', '','');
		$this -> entryText('P10O3','P10O3', '','');
		$this -> entryText('P10O4','P10O4', '','');
		$this -> entryText('P10O5','P10O5', '','');
		$this -> entryText('P11O1','P11O1', '','');
		$this -> entryText('P11O2','P11O2', '','');
		$this -> entryText('P11O3','P11O3', '','');
		$this -> entryText('P11O4','P11O4', '','');
		$this -> entryText('P11O5','P11O5', '','');
		$this -> entryText('P11O6','P11O6', '','');
		$this -> entryText('P11O7','P11O7', '','');
		$this -> entryText('P11O8','P11O8', '','');
		$this -> entryText('P14O1','P14O1', '','');
		$this -> entryText('P14O2','P14O2', '','');
		$this -> entryText('P14O3','P14O3', '','');
		$this -> entryText('P14O4','P14O4', '','');
		$this -> entryText('P14O5','P14O5', '','');
		$this -> entryText('P14O6','P14O6', '','');
		$this -> entryText('P14O7','P14O7', '','');
		$this -> entryText('P14O8','P14O8', '','');
		$this -> entryText('P14O9','P14O9', '','');
		$this -> entryText('P14O10','P14O10', '','');
		$this -> entryText('P14O11','P14O11', '','');
		echo("</table>");
	}

}
?>